from enum import StrEnum


class ApplicationStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    SCORED = "SCORED"
    QUEUED = "QUEUED"
    NEEDS_HUMAN = "NEEDS_HUMAN"
    SUBMITTED = "SUBMITTED"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"


class JobSource(StrEnum):
    WELLFOUND = "WELLFOUND"
    NAUKRI = "NAUKRI"
    INSTAHYRE = "INSTAHYRE"
    COMPANY_SITE = "COMPANY_SITE"
    LINKEDIN = "LINKEDIN"
    MANUAL = "MANUAL"


class DecisionReason(StrEnum):
    SCORE_AUTO_QUEUE = "SCORE_AUTO_QUEUE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    DREAM_COMPANY = "DREAM_COMPANY"
    DAILY_CAP_REACHED = "DAILY_CAP_REACHED"
    USER_REQUESTED = "USER_REQUESTED"
    LINKEDIN_SEMI_AUTOMATIC = "LINKEDIN_SEMI_AUTOMATIC"


class AuditEventType(StrEnum):
    JOB_DISCOVERED = "JOB_DISCOVERED"
    JOB_SCORED = "JOB_SCORED"
    STATUS_CHANGED = "STATUS_CHANGED"
    SCREENSHOT_CAPTURED = "SCREENSHOT_CAPTURED"
    HUMAN_REVIEW_REQUESTED = "HUMAN_REVIEW_REQUESTED"
